spring.application.name=pos-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DBMS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.personal.store_api.controller=DEBUG
logging.level.com.personal.store_api.service=DEBUG

spring.devtools.restart.enabled=true

jwt.signerKey=fd0874c323c8f2fb6c59e865fb22ad5f70f43604ddecc1fb7ca2e2489d5d97c0
jwt.valid-duration: 3600
jwt.refreshable-duration: 36000

# Cloudinary Configuration
cloudinary.cloud-name=dnnwckanv
cloudinary.api-key=469137543286286
cloudinary.api-secret=wEoAgqN-kFubpoawenF9JbTlYk4
cloudinary.folder=store-api

# Elasticsearch Configuration
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.connection-timeout=30s
spring.elasticsearch.username=elastic
spring.elasticsearch.password=FE86BQxhqoiMA9aikqzJ

# Stripe
stripe.sr-key=${STRIPE_SECRET}
stripe.publishable-key=pk_test_51T7oh63BeSyWyUb2rt2VVW0HzRKWZOLiS2hb15qoMKdF49EE93fRo1LuKFIotQ0WgI6iApKesi2cYWspYaHC2DBe00saUfp5eg
stripe.webhook-secret=whsec_99f55ea039f35b550c67a60f8a114f42c7d05f1eb0a2732ad84cdc0b4d5cbf09

# Redis Configuration
spring.data.redis.host=localhost
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000