export default [
  {
    id: 1001,
    customer_email: "chandlerjacobi@test.net",
    status: "pending",
    total_amount: 989.4,
    note: "Please deliver before 5 PM",
    user_id: 1,
    customer: {
      name: "Chandler Jacobi",
      phone: "+1-555-0101",
      email: "chandlerjacobi@test.net",
    },
    created_at: "2020-02-03T04:13:15.000Z",
    updated_at: "2020-02-03T10:30:00.000Z",
    order_items: [
      {
        id: 1,
        product_name: "Nike Air Max",
        sku: "NK-AM-001",
        size: "42",
        color: "Black",
        quantity: 2,
        selling_price: 199.0,
      },
      {
        id: 2,
        product_name: "Adidas T-Shirt",
        sku: "AD-TS-002",
        size: "L",
        color: "White",
        quantity: 3,
        selling_price: 49.8,
      },
    ],
  },
  {
    id: 1002,
    customer_email: "harrypeter@test.net",
    status: "completed",
    total_amount: 471.44,
    note: "Gift wrap requested",
    user_id: 2,
    customer: {
      name: "Harry Peter",
      phone: "+1-555-0102",
      email: "harrypeter@test.net",
    },
    created_at: "2019-11-29T10:43:17.000Z",
    updated_at: "2019-11-30T14:20:00.000Z",
    order_items: [
      {
        id: 3,
        product_name: "Apple Watch Series 5",
        sku: "AP-AW-003",
        size: "44mm",
        color: "Silver",
        quantity: 1,
        selling_price: 399.0,
      },
      {
        id: 4,
        product_name: "Watch Band",
        sku: "AP-WB-004",
        size: "One Size",
        color: "Black",
        quantity: 2,
        selling_price: 36.22,
      },
    ],
  },
  {
    id: 1003,
    customer_email: "judith.es@test.net",
    status: "pending",
    total_amount: 934.24,
    note: "Call before delivery",
    user_id: 3,
    customer: {
      name: "Judith Espanaso",
      phone: "+1-555-0103",
      email: "judith.es@test.net",
    },
    created_at: "2020-04-03T03:07:53.000Z",
    updated_at: "2020-04-03T09:15:00.000Z",
    order_items: [
      {
        id: 5,
        product_name: "Samsung Galaxy S20",
        sku: "SM-GS-005",
        size: "128GB",
        color: "Blue",
        quantity: 1,
        selling_price: 899.0,
      },
      {
        id: 6,
        product_name: "Phone Case",
        sku: "SM-PC-006",
        size: "S20",
        color: "Clear",
        quantity: 1,
        selling_price: 35.24,
      },
    ],
  },
  {
    id: 1004,
    customer_email: "jjmike@test.net",
    status: "completed",
    total_amount: 351.28,
    note: "",
    user_id: 4,
    customer: {
      name: "Jason Mike",
      phone: "+1-555-0104",
      email: "jjmike@test.net",
    },
    created_at: "2019-06-21T20:21:55.000Z",
    updated_at: "2019-06-22T11:00:00.000Z",
    order_items: [
      {
        id: 7,
        product_name: "Sony Headphones",
        sku: "SN-HP-007",
        size: "Over-ear",
        color: "Black",
        quantity: 1,
        selling_price: 299.0,
      },
      {
        id: 8,
        product_name: "Audio Cable",
        sku: "SN-AC-008",
        size: "3.5mm",
        color: "Black",
        quantity: 2,
        selling_price: 26.14,
      },
    ],
  },
  {
    id: 1005,
    customer_email: "shane_smith@test.net",
    status: "pending",
    total_amount: 355.3,
    note: "Leave at door if not home",
    user_id: 5,
    customer: {
      name: "Smith Shane",
      phone: "+1-555-0105",
      email: "shane_smith@test.net",
    },
    created_at: "2019-08-28T15:31:43.000Z",
    updated_at: "2019-08-28T18:45:00.000Z",
    order_items: [
      {
        id: 9,
        product_name: "HP Laptop",
        sku: "HP-LP-009",
        size: "15.6 inch",
        color: "Silver",
        quantity: 1,
        selling_price: 355.3,
      },
    ],
  },
];
