export default [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/300",
    name: "Chandler Jacobi",
    email: "chandlerjacobi@test.net",
    phone: "+1-555-0101",
    dob: "1990-05-15",
    gender: "Male",
    address: "123 Main St, New York, NY 10001",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: true,
    messages: [
      { flag: "from_client", text: "Hello there..," },
      { flag: "to_client", text: "Hello sir, How can I help you" },
      {
        flag: "from_client",
        text: "I need to know the price of New Nike Shoues",
      },
      {
        flag: "to_client",
        text: "Newset Nike one will be $199.00 sir",
      },
      {
        flag: "from_client",
        text: "Okay, Do you deliver it my home after purchase..?",
      },
      {
        flag: "to_client",
        text:
          "Yes sir, But it may take at least 1 Day... Are you okay with that time..?",
      },
    ],
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/300",
    name: "Harry Peter",
    email: "harrypeter@test.net",
    phone: "+1-555-0102",
    dob: "1988-08-22",
    gender: "Male",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: false,
    messages: [
      { flag: "from_client", text: "Hello there..," },
      { flag: "to_client", text: "Hello sir, How can I help you" },
      {
        flag: "from_client",
        text: "I need to buy latest revealed Apple Watch",
      },
    ],
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/300",
    name: "Judith Espanaso",
    email: "judith.es@test.net",
    phone: "+1-555-0103",
    dob: "1992-03-10",
    gender: "Female",
    address: "789 Pine Rd, Chicago, IL 60601",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: true,
    messages: [{ flag: "from_client", text: "Hello..," }],
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/300",
    name: "Jason Mike",
    email: "jjmike@test.net",
    phone: "+1-555-0104",
    dob: "1985-11-30",
    gender: "Male",
    address: "321 Elm St, Houston, TX 77001",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: false,
    messages: [
      { flag: "from_client", text: "Hello there..," },
      { flag: "to_client", text: "Hello sir, How can I help you" },
      {
        flag: "from_client",
        text: "I need to know the price of New Addidas Shoues",
      },
    ],
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/300",
    name: "Smith Shane",
    email: "shane_smith@test.net",
    phone: "+1-555-0105",
    dob: "1995-07-18",
    gender: "Male",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: false,
    messages: null,
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/300",
    name: "Adam Joe",
    email: "adam.jj@test.net",
    phone: "+1-555-0106",
    dob: "1991-01-25",
    gender: "Male",
    address: "987 Cedar Ln, Philadelphia, PA 19101",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: true,
    messages: [
      { flag: "from_client", text: "Hello there..," },
      { flag: "to_client", text: "Hello sir, How can I help you" },
      {
        flag: "from_client",
        text: "I need to know the price of New Addidas Shoues",
      },
    ],
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/300",
    name: "Josheph Churchille",
    email: "joe.churchile@test.net",
    phone: "+1-555-0107",
    dob: "1989-12-05",
    gender: "Male",
    address: "147 Birch Blvd, San Antonio, TX 78201",
    joined_on: "Mon Feb 03 2020 04:13:15 GMT-0300 (Brasilia Standard Time)",
    state: false,
    messages: null,
  },
];
